list(APPEND CMAKE_FIND_ROOT_PATH $ENV{SECOND_FIND_ROOT_PATH})
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")

if (NOT $ENV{APPLE_PLATFORM} MATCHES "macosx")
    set(UNIX True)
    set(APPLE True)

    set(CMAKE_MACOSX_BUNDLE TRUE)
    set(CMAKE_CROSSCOMPILING TRUE)

    set(CMAKE_OSX_SYSROOT $ENV{APPLE_SDK_PATH} CACHE PATH "Sysroot used for Apple support")
endif()
